#!/bin/bash

function
run_user_operation ()
{
  if["$1" == "create"];
  then useradd $2 elif["$1" == "list"] &&["$2" == "--sudo-only"];
  then getent group sudo elif["$1" == "list"];
then getent passwd | cut - d:-f1
  else
echo "Invalid arguments for user command Use --help for help." fi}

function
run_file_operation ()
{

  filename = "$1"
    ls_output = $ (sudo ls - l "$filename")
    file_permissions = $ (echo "$ls_output" | awk '{print $1}')
    file_size = $ (echo "$ls_output" | awk '{print $5}')
    file_owner = $ (echo "$ls_output" | awk '{print $3}')
    file_modify = $ (echo "$ls_output" | awk '{print $6, $7, $8}')
#Displaying formatted information
    echo "File: $filename"
    echo "Access: $file_permissions"
    echo "Size(B): $file_size"
    echo "Owner: $file_owner" echo "Modify: $file_modify" if["$1" != *"--" *];
  then elif["$1" == "--size"];
  then echo "$file_size" elif["$1" == "--permissions"];
  then echo "$file_permissions" elif["$1" == "--owner"];
  then echo "$file_owner" elif["$1" == "--last-modified"];
  then echo "$file_modify"
  else
echo "Invalid arguments for file  command Use --help for help." fi}

function
get_help ()
{

echo "Usage: internsctl [OPTIONS]"
    echo "Custom Linux Command for Operations"
    echo ""
    echo "Options:"
    echo "  --help   "
    echo "  --version "
    echo "  cpu getinfo "
    echo "  memory getinfo "
    echo "  Enter username: <username> Create a new user"
    echo "  user list " echo "  user list --sudo-only"}
if["$1" == "memory"]
  &&["$2" == "getinfo"];
then free - h elif["$1" == "cpu"] &&["$2" == "getinfo"];
then lscpu elif["$1" == "file"] &&["$2" == "getinfo"];
then run_file_operation elif["$1" == "user"];
then run_user_operation "$2" "$3" elif["$1" == "--version"];
then echo "v0.1.0" elif["$1" == "--help"];
then get_help
else
echo "Invalid command. Use '--help' for help." fi 53, 1

